version: '3'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: activiti
    ports:
      - 3306:3306
    volumes:
      - ./activiti.sql:/docker-entrypoint-initdb.d/data.sql
  app:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - 8080:8080
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/activiti?nullCatalogMeansCurrent=true&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&allowMultiQueries=true
      SPRING_DATASOURCE_USERNAME: root
      MYSQL_ROOT_PASSWORD: 123456